Cleaned up recent libc patch
Now checks whether in6_pktinfo should be defined or if it's already been taken
care of by the libc.

Signed-off-by: Jeremie Corbier <jeremie@famille-corbier.net>

diff --git a/debian/patches/102_libc6-2.9-fixes.diff b/debian/patches/102_libc6-2.9-fixes.diff
--- a/debian/patches/102_libc6-2.9-fixes.diff
+++ b/debian/patches/102_libc6-2.9-fixes.diff
@@ -2240,19 +2240,97 @@ Index: wide-dhcpv6/config.c
  		 pool->name, in6addr2str(addr, 0));
  
  	return (0);
+Index: wide-dhcpv6/configure
+===================================================================
+--- wide-dhcpv6.orig/configure
++++ wide-dhcpv6/configure
+@@ -6013,7 +6013,55 @@
+ done
+ 
+ 
+-          ac_config_files="$ac_config_files Makefile"
++{ echo "$as_me:$LINENO: checking whether libc defines struct in6_pktinfo" >&5
++echo $ECHO_N "checking whether libc defines struct in6_pktinfo... $ECHO_C" >&6; }
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++#include <netinet/in.h>
++int
++main ()
++{
++struct in6_pktinfo p6;
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext
++if { (ac_try="$ac_compile"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_compile") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } && {
++	 test -z "$ac_c_werror_flag" ||
++	 test ! -s conftest.err
++       } && test -s conftest.$ac_objext; then
++  { echo "$as_me:$LINENO: result: yes" >&5
++echo "${ECHO_T}yes" >&6; }
++  CFLAGS="$CFLAGS -DHAVE_IN6_PKTINFO"
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++	{ echo "$as_me:$LINENO: result: no" >&5
++echo "${ECHO_T}no" >&6; }
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
++
++ac_config_files="$ac_config_files Makefile"
++
+ cat >confcache <<\_ACEOF
+ # This file is a shell script that caches the results of configure
+ # tests run on this system so they can be shared between configure
+Index: wide-dhcpv6/configure.in
+===================================================================
+--- wide-dhcpv6.orig/configure.in
++++ wide-dhcpv6/configure.in
+@@ -236,4 +236,11 @@
+ 
+ AC_CHECK_HEADERS(stdarg.h)
+ 
++AC_MSG_CHECKING(whether libc defines struct in6_pktinfo)
++AC_TRY_COMPILE([#include <netinet/in.h>],
++ [struct in6_pktinfo p6;],
++ [AC_MSG_RESULT(yes)
++  CFLAGS="$CFLAGS -DHAVE_IN6_PKTINFO"],
++ [AC_MSG_RESULT(no)])
++
+ AC_OUTPUT(Makefile)
 Index: wide-dhcpv6/dhcp6.h
 ===================================================================
 --- wide-dhcpv6.orig/dhcp6.h
 +++ wide-dhcpv6/dhcp6.h
-@@ -108,6 +108,12 @@
+@@ -108,6 +108,13 @@
  #define DHCP6_IRT_DEFAULT 86400	/* 1 day */
  #define DHCP6_IRT_MINIMUM 600
  
-+/* Add missing definition of in6_pktinfo so we don't have to use _GNU_SOURCE*/
++#ifndef HAVE_IN6_PKTINFO
 +struct in6_pktinfo {
 +	struct in6_addr ipi6_addr;  /* src/dst IPv6 address */
 +	unsigned int ipi6_ifindex;  /* send/recv interface index */
 +};
++#endif
 +
  /* DUID: DHCP unique Identifier */
  struct duid {
